### ISSUE TITLE
Help on running website.

### ISSUE THREAD

**Issue by DangerouserTeam** [RobloxLabs/web#6]
How can i run this web? Is there a small tutorial? **Help!**

**Comment by Yebonow** [comment]
just use iis with asp.net

**Comment by DangerouserTeam** [comment]
oh! thats what the problem was. tysm, i was using visual studio to run that lol

**Comment by AlexDescent** [comment]
@Yebonow Mind helping me run it?

**Comment by Yebonow** [comment]
@AlexDescent are you using the web forms or core branch

**Comment by AlexDescent** [comment]
> @AlexDescent are you using the web forms or core branch

If you could help me that would be wonderful my discord is cloutsyy

**Comment by 0drownedsoul0** [comment]
> @AlexDescent are you using the web forms or core branch

hey can you please help me run it?

**Comment by Yebonow** [comment]
> > @AlexDescent are you using the web forms or core branch
> 
> hey can you please help me run it?

maybe

**Comment by 0drownedsoul0** [comment]
> > > @AlexDescent are you using the web forms or core branch
> > 
> > 
> > hey can you please help me run it?
> 
> maybe

Can you please tell me how do I run it?

**Comment by BrentDaMage** [comment]
Guys it's missing dependencies that I couldn't make open-source. Unless you remake them, the website is not going to build or run.

**Comment by 0drownedsoul0** [comment]
> Guys it's missing dependencies that I couldn't make open-source. Unless you remake them, the website is not going to build or run.

That's sad

**Comment by 0drownedsoul0** [comment]
> Guys it's missing dependencies that I couldn't make open-source. Unless you remake them, the website is not going to build or run.

But why can't you make them open-source?

**Comment by Yebonow** [comment]
dementia

**Comment by EasternBloxxer** [comment]
> Guys it's missing dependencies that I couldn't make open-source. Unless you remake them, the website is not going to build or run.

You should share them with me because i asked Nicely,
